const GRID_ORIGIN = Vector2(88, 18)
const GRID_STRIDE = 9
const CREATE_PLAYER_GRID_ORIGIN = Vector2(108, 38)
const CREATE_PLAYER_GRID_STRIDE = 13
const TRANSITION_STRIDE = 8
const GRID_SIZE = 16
const PLAYER_GRID_SIZE = 8
const PLAYER_AREA_START = 4
